### PR TITLE
add new functions from liberfa and bump to version 1.3.0

### PR DESCRIPTION
**Pull request by nirinA**
those patches add new functions from liberfa-1.3.0, and their respective tests. @kbarbary can you, please, build and check for the windows binaries? and also update appveyor.yml.

### CODE REVIEW

**Comment by kbarbary** [comment]
I built and uploaded windows binaries. The windows url in `build.jl` should be changed to
```
"https://dl.bintray.com/kbarbary/generic/erfa-$(version)-win$(Sys.WORD_SIZE).7z"
```
(I added the version to the archive name to avoid conflict with previous versions)

I don't think `appveyor.yml` needs updating, except to updated tested julia version from 0.3/0.4/nightly to 0.4/0.5/nightly.

**Comment by nirinA** [comment]
thank you very much. i will update the url and also the version for both `appveyor.yml` and `.travis.yml`.

**Comment by nirinA** [comment]
do we also need to update `REQUIRE` from julia-0.3 to julia-0.4?

**Comment by kbarbary** [comment]
Probably should update REQUIRE since we'll no longer be testing against 0.3.

**Comment by kbarbary** [comment]
Looks good to me.

**Comment by crbinz** [comment]
Should this be tagged as a new `ERFA.jl` release?

**Comment by nirinA** [comment]
this surely needs a new tag. something like using `Pkg.tag(...)`; but the last time i did this, i completely broke my Julia installation, so i am a bit unwilling to do it. unless someone else will do it before, i may try the next weekend.

**Comment by kbarbary** [comment]
I could do it, but it would be nice to have someone else set up to tag releases. Maybe you can give it another shot @nirinA ? I'm happy to help debug METADATA problems.

**Comment by nirinA** [comment]
i have a new and fresh 0.5 installation and will try again. but what is preferable: using PkgDev or using git? something as simple as `Pkg.tag("ERFA", "v0.1.3")` would be so nice.

**Comment by kbarbary** [comment]
Personally I use a combination.

- `PkgDev.tag("ERFA", :minor)` will add a commit to your local METADATA repository. (It also adds a tag to the ERFA repo, but that tag isn't used by Julia; it's just nice to have).
- I manually push the METADATA change to my METADATA github fork using git.
- submit a PR on github.
- push the new tag to ERFA to the upstream ERFA repo.

`PkgDev.publish()` can do the second (and third?) steps for you, but is prone to getting in a confusing state, particularly if you make a mistake.

I also usually manually pull changes to METADATA from upstream before doing the above steps. This just makes the METADATA history simpler and shouldn't really be necessary.

**Comment by nirinA** [comment]
thanks, Kyle. i will try this.

**Comment by crbinz** [comment]
For what it's worth, Kyle's method is exactly how I do it as well.

**Comment by nirinA** [comment]
i'm trying to tag the new release. i've  done `PkgDev.tag("ERFA", :minor)` and this gives me `INFO: Tagging ERFA v0.2.0`. is this right or should be this `PkgDev.tag("ERFA", :patch)` ?

**Comment by kbarbary** [comment]
I think it should indeed be minor (v0.2.0) because this version adds new features. See semver.org for more on semantic versioning.

**Comment by nirinA** [comment]
agreed with the tag version.
but i definitely have some troubles with this tag thing! when pushing to my METADATA fork, i now get this:
```
To https://github.com/nirinA/METADATA.jl
 ! [rejected]        metadata-v2 -> metadata-v2 (fetch first)
error: failed to push some refs to 'https://github.com/nirinA/METADATA.jl'
```
maybe i did something crazy again yesterday when i did the pull.

**Comment by kbarbary** [comment]
I would probably just do the following (assuming you have an `upstream` remote set to `https://github.com/JuliaLang/METADATA.jl` and `origin` is set to your github fork):

```
git fetch upstream
git rebase upstream/metadata-v2
git push -f origin metadata-v2
```

**Comment by nirinA** [comment]
the above commands succeeded and i pushed the PR as:
https://github.com/JuliaLang/METADATA.jl/pull/7017
the check on travis there failed though.

**Comment by nirinA** [comment]
and tagged the new release of ERFA.jl.

**Comment by kbarbary** [comment]
It looks like you were on the wrong branch of ERFA when you did `PkgDev.tag()`... otherwise the requirements would have properly specified `julia 0.4`. Looking at the PR in JuliaLang/METADATA.jl#7017, the commit you tagged as v0.2.0 is a959499, but the latest commit to master is 8d284d0.

**Comment by kbarbary** [comment]
To recover is an annoying process. First you need to get back to the state before you tagged:

```
# (go to your METADATA repo)
git reset --hard upstream/metadata-v2  # discard your commit (desctructive)
git fetch upstream
git merge upstream/metadata-v2  # get latest commits (not strictly necessary)

# (go to your ERFA repo)
git tag -d v0.2.0  # delete the tag
git push upstream :v0.2.0  # delete the tag on the JuliaAstro remote
```

now you should be set to do the process over again. Make sure you're on ERFA master and that it is up-to-date with the JuliaAstro remote before starting though!

Note that you don't need to redo the PR; pushing with `git push -f origin metadata-v2` will update the PR with the new, correct, commit.

**Comment by nirinA** [comment]
annoying indeed, and very much confusing process without real care. `REQUIRE` also seems to need an update, `BinDeps` and `Compat` need minimum version; i will just pick versions from `Pkg.status()`: BinDeps 0.4.5 and Compat 0.9.3.
if i can recover all this correctly, i think i will no longer use PkgDev, just `git tag v0.2.0`.

**Comment by kbarbary** [comment]
The git tag is largely irrelevant. The important part for distributing the code to other users is the commit that is made in the METADATA repo. So you either need to write that yourself in the right format, or use `Pkg.tag()`/`PkgDev.tag()`. Simply doing `git tag` is not enough.

Fortunately an overhaul of the package system is [planned](https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md).

**Comment by nirinA** [comment]
i think i did correctly the process to recover the METADATA repo and delete the tag on ERFA. also updated REQUIRE. but i would like to be sure about what i should do before going on, other error will just be disturbing. so, after `PkgDev.tag("ERFA", :minor)`, do i need to submit this to my METADATA github fork? does this github fork also need a reset?

even before issuing PkgDev.tag, what is the command in Pkg or PkgDev to show me the latest commit?

**Comment by kbarbary** [comment]
> Do i need to submit this to my METADATA github fork? does this github fork also need a reset?

As I said above, you should be able to just `git push -f origin metadata-v2` (assuming `origin` is your METADATA github fork).

> even before issuing PkgDev.tag, what is the command in Pkg or PkgDev to show me the latest commit?

Yes, definitely check that ERFA and METADATA are where you want them to be before tagging (don't forget to fetch ERFA master if you haven't!). I would just use `git log` in the relevant repo for this.

**Comment by nirinA** [comment]
tkelman reviewed the patch on METADATA and said the BinDeps and Compat versions, being the latest, are too conservative and not accurate. i'll update these versions to BinDeps 0.3.21 and Compat 0.7.10, they are the current versions on my julia 0.4.2 installation. so there will be another new push to METADATA before the new ERFA release will be tagged effectively.

**Comment by nirinA** [comment]
that was laborious, but we have now the new tagged 0.2.0 release. thanks you, Kyle, for your help.

**Pull request merged**
